%% Plotting script for Project 3 FYS4150
%Here the files generated by the Qt C++ code is read and plots are being
%made. 
%% Oppgave 3c)    Stability of two-body system

%Read in the files from the runs with only earth

%-----------------dT = 1day ------------------
%Earth position verlet.
fid = fopen('Day_VerletValuesEarth.txt');
VVEarth_day = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Earth position euler
fid = fopen('Day_EulerValues.txt');
FEEarth_day = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Conserved values euler. 
fid = fopen('Day_ConservedEulerValues.txt');
CEuler_day = cell2mat(textscan(fid,'%f %f %f'));
fclose(fid);

%Conserved values verlet. 
fid = fopen('Day_ConservedVerletValues.txt');
CVerlet_day = cell2mat(textscan(fid,'%f %f %f'));
fclose(fid);
%----------------------------------------------

%-----------------dT = 1week ------------------
%Earth position verlet.
fid = fopen('Week_VerletValuesEarth.txt');
VVEarth_week = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Earth position euler
fid = fopen('Week_EulerValues.txt');
FEEarth_week = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Conserved values euler. 
fid = fopen('Week_ConservedEulerValues.txt');
CEuler_week = cell2mat(textscan(fid,'%f %f %f'));
fclose(fid);

%Conserved values verlet. 
fid = fopen('Week_ConservedVerletValues.txt');
CVerlet_week = cell2mat(textscan(fid,'%f %f %f'));
fclose(fid);
%----------------------------------------------

%-----------------dT = 1mnd ------------------
%Earth position verlet.
fid = fopen('Month_VerletValuesEarth.txt');
VVEarth_month = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Earth position euler
fid = fopen('Month_EulerValues.txt');
FEEarth_month = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Conserved values euler. 
fid = fopen('Month_ConservedEulerValues.txt');
CEuler_month = cell2mat(textscan(fid,'%f %f %f'));
fclose(fid);

%Conserved values verlet. 
fid = fopen('Month_ConservedVerletValues.txt');
CVerlet_month = cell2mat(textscan(fid,'%f %f %f'));
fclose(fid);
%----------------------------------------------

%-----------------dT = 2mnd ------------------
%Earth position verlet.
fid = fopen('2Month_VerletValuesEarth.txt');
VVEarth_2month = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Earth position euler
fid = fopen('2Month_EulerValues.txt');
FEEarth_2month = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Conserved values euler. 
fid = fopen('2Month_ConservedEulerValues.txt');
CEuler_2month = cell2mat(textscan(fid,'%f %f %f'));
fclose(fid);

%Conserved values verlet. 
fid = fopen('2Month_ConservedVerletValues.txt');
CVerlet_2month = cell2mat(textscan(fid,'%f %f %f'));
fclose(fid);
%----------------------------------------------------------------------

%Position Plot
%Subplot with 20year simulations for
%different timesteps (1day, 1week, 1mnd, 2mnd, 6mnd, 1year)
figure(1)
title('Totaltime = 20 Year, dT = 1 day');
h1 = plot(FEEarth_day(:,1),FEEarth_day(:,2),'red');
hold on
h2 = plot(VVEarth_day(:,1),VVEarth_day(:,2),'blue');
legend([h1 h2],['Forward Euler'],['Velocity Verlet'])
xlim([-2,2])
ylim([-2,2])
xlabel('AU')
ylabel('AU')

figure(2)
title('Totaltime = 20 Year, dT = 1 week');
h1 = plot(FEEarth_week(:,1),FEEarth_week(:,2),'red');
hold on
h2 = plot(VVEarth_week(:,1),VVEarth_week(:,2),'blue');
legend([h1 h2],['Forward Euler'],['Velocity Verlet'])
xlim([-2,2])
ylim([-2,2])
xlabel('AU')
ylabel('AU')

figure(3)
title('Totaltime = 20 Year, dT = 1 month');
h1 = plot(FEEarth_month(:,1),FEEarth_month(:,2),'red');
hold on
h2 = plot(VVEarth_month(:,1),VVEarth_month(:,2),'blue');
legend([h1 h2],['Forward Euler'],['Velocity Verlet'])
xlim([-2,2])
ylim([-2,2])
xlabel('AU')
ylabel('AU')

figure(4)
title('Totaltime = 20 Year, dT = 2 months');
h1 = plot(FEEarth_2month(:,1),FEEarth_2month(:,2),'red');
hold on
h2 = plot(VVEarth_2month(:,1),VVEarth_2month(:,2),'blue');
legend([h1 h2],['Forward Euler'],['Velocity Verlet'])
xlim([-2,2])
ylim([-2,2])
xlabel('AU')
ylabel('AU')

%----------------------------------------------------------------------

%Energy plot (kinetic, potential, total)
%Subplot with 20year simulations for
%different timesteps (1day (stable), 2mnd (unstable))
figure(5)
title('Totaltime = 20 Year, dT = 1 day');
h1 = plot(CEuler_day(:,1)/CEuler_day(1,1) ,'red');
hold on
h2 = plot(CVerlet_day(:,1)/CVerlet_day(1,1),'blue');
legend([h1 h2],['Kin. Energy Forward Euler'],['Kin. Energy Velocity Verlet'])
xlabel('# timestep')
ylabel('Relative to initial value')

%Potential energy 1day
figure(6)
title('Totaltime = 20 Year, dT = 1 day');
h1 = plot(CEuler_day(:,2)/CEuler_day(1,2),'red');
hold on
h2 = plot(CVerlet_day(:,2)/CVerlet_day(1,2),'blue');
legend([h1 h2],['Pot. Energy Forward Euler'],['Pot. Energy Velocity Verlet'])
xlabel('# timestep')
ylabel('Relative to initial value')

%Total Energy 1day
figure(7)
title('Totaltime = 20 Year, dT = 1 day');
h1 = plot((CEuler_day(:,1) + CEuler_day(:,2))/(CEuler_day(1,1) + CEuler_day(1,2)) ,'red');
hold on
h2 = plot((CVerlet_day(:,1)  + CVerlet_day(:,2))/(CVerlet_day(1,1) + CVerlet_day(1,2)),'blue');
legend([h1 h2],['Tot. Energy Forward Euler'],['Tot. Energy Velocity Verlet'])
xlabel('# timestep')
ylabel('Relative to initial value')

%Kinetic energy 2mnd
figure(8)
title('Totaltime = 20 Year, dT = 2mnd');
h1 = plot(CEuler_2month(:,1)/CEuler_2month(1,1),'red');
hold on
h2 = plot(CVerlet_2month(:,1)/CVerlet_2month(1,1),'blue');
legend([h1 h2],['Kin. Energy Forward Euler'],['Kin. Energy Velocity Verlet'])
xlabel('# timestep')
ylabel('Relative to initial value')

%Potential energy 2mnd
figure(9)
title('Totaltime = 20 Year, dT = 2mnd');
h1 = plot(CEuler_2month(:,2)/CEuler_2month(1,2),'red');
hold on
h2 = plot(CVerlet_2month(:,2)/CVerlet_2month(1,2),'blue');
legend([h1 h2],['Pot. Energy Forward Euler'],['Pot. Energy Velocity Verlet'])
xlabel('# timestep')
ylabel('Relative to initial value')

%Total Energy 2mnd
figure(10)
title('Totaltime = 20 Year, dT = 2mnd');
h1 = plot((CEuler_2month(:,1) + CEuler_2month(:,2))/(CEuler_2month(1,1) + CEuler_2month(1,2)),'red');
hold on
h2 = plot((CVerlet_2month(:,1) + CVerlet_2month(:,2))/(CVerlet_2month(1,1) + CVerlet_2month(1,2)),'blue');
legend([h1 h2],['Tot. Energy Forward Euler'],['Tot. Energy Velocity Verlet'])
xlabel('# timestep')
ylabel('Relative to initial value')

%-----------------------------------------------------------------------

%Angular momentum plot 
%Subplot with 20year simulations for
%different timesteps (1day (stable), 2mnd (unstable))

%Angular momentum 1day
figure(11)
title('Totaltime = 20 Year, dT = 1day');
h1 = plot((CEuler_day(:,3)-CEuler_day(1,3))/CEuler_day(1,3),'red');
hold on
h2 = plot((CVerlet_day(:,3)-CVerlet_day(1,3))/CVerlet_day(1,3),'blue');
legend([h1 h2],['Ang. Momentum Forward Euler'],['Ang. Momentum Velocity Verlet'])
xlabel('# timestep')
ylabel('Relative to initial value')

%Angular momentum 2mnd
figure(12)
title('Totaltime = 20 Year, dT = 2mnd');
h1 = plot(CEuler_2month(:,3)/CEuler_2month(1,3),'red');
hold on
h2 = plot(CVerlet_2month(:,3)/CVerlet_2month(1,3),'blue');
legend([h1 h2],['Ang. Momentum Forward Euler'],['Ang. Momentum Velocity Verlet'])
xlabel('# timestep')
ylabel('Relative to initial value')
ylim([-50,300])

%% Oppgave 3d)   Escape Velocity and change of F

%Read in files
%----------------- Initial speed = 2.85Pi ---------

%Earth position verlet.
fid = fopen('Earth_28Pi.txt');
Earth_28pi = cell2mat(textscan(fid,'%f %f'));
fclose(fid);


%----------------------------------------------

%----------------- Initial speed = 2.8Pi ---------

%Earth position verlet.
fid = fopen('Earth_285Pi.txt');
Earth_285pi = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%----------------------------------------------

%------------ Different Force, r^2.8 ---------

%Earth position verlet.
fid = fopen('Earth_R38.txt');
Earth_R28 = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%----------------------------------------------

%------------ Different Force, r^2.99 ---------

%Earth position verlet.
fid = fopen('Earth_R3999.txt');
Earth_R2999 = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%----------------------------------------------

%Position Plot
%Subplots of different initial speeds(3Pi, Pi, etc)
%1000 year simulations, timestep = 1day

%----------------- Initial speed = 2.8Pi ---------

figure(13)
title('Totaltime = 1000 Year, dT = 1day, V_0 = 2.8Pi');
h1 = plot(Earth_28pi(:,1),Earth_28pi(:,2),'red');
legend('V_0 = 2.8*Pi')
xlabel('AU')
ylabel('AU')
xlim([-40,40])
ylim([-40,40])

%-------------------------------------------

%----------------- Initial speed = 2.85Pi ---------

figure(14)
title('Totaltime = 1000 Year, dT = 1day, V_0 = 2.85Pi');
h1 = plot(Earth_285pi(:,1),Earth_285pi(:,2),'red');
legend('V_0 = 2.85*Pi')
xlabel('AU')
ylabel('AU')
xlim([-1000,1000])
ylim([-1000,1000])

%-------------------------------------------

%----------------- R = 2.8 ---------

figure(15)
title('Totaltime = 1000 Year, dT = 1day, F ~ 1/r^{2.8}');
h1 = plot(Earth_R28(:,1),Earth_R28(:,2),'red');
legend('Position of Earth, if F ~ 1/R^{2.8}')
xlim([-2,2])
ylim([-2,2])
grid on
xlabel('AU')
ylabel('AU')

%-------------------------------------------

%----------------- R = 2.99 ------------------

figure(16)
title('Totaltime = 1000 Year, dT = 1day, F ~ 1/r^{2.999}');
h1 = plot(Earth_R2999(:,1),Earth_R2999(:,2),'red');
legend('Position of Earth, if F ~ 1/R^{2.999}')
xlim([-2,2])
ylim([-2,2])
grid on
xlabel('AU')
ylabel('AU')


%-------------------------------------------

%Position Plot
%Subplots of different exponents between 2 and 3.
%? year simulations, timeste = ?

%% Oppgave 3e) Three body system
%Read in correct files
%Earth position dt = 1day.
fid = fopen('Earth_1day_JE.txt');
JE_Earth_day = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Jupiter position dt = 1 day.
fid = fopen('Jupiter_1day_JE.txt');
JE_Jupiter_day = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Earth position dt = 2mnd.
fid = fopen('Earth_2mnd_JE.txt');
JE_Earth_2mnd = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Jupiter position dt = 2mnd.
fid = fopen('Jupiter_2mnd_JE.txt');
JE_Jupiter_2mnd = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Conserved values dt = 1day
fid = fopen('JE_Conserved_1day.txt');
JE_Cons_1day = cell2mat(textscan(fid,'%f %f %f'));
fclose(fid);

%Conserved values dt = 2mnd
fid = fopen('JE_Conserved_2mnd.txt');
JE_Cons_2mnd = cell2mat(textscan(fid,'%f %f %f'));
fclose(fid);

%Earth position dt = 1day, J10
fid = fopen('JE_Earth_J10.txt');
JE_Earth_J10 = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Jupiter position dt = 1day, J10
fid = fopen('JE_Jupiter_J10.txt');
JE_Jupiter_J10 = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Earth position dt = 1day J1000
fid = fopen('JE_Earth_J1000.txt');
JE_Earth_J1000 = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Jupiter position dt = 1day J1000
fid = fopen('JE_Jupiter_J1000.txt');
JE_Jupiter_J1000 = cell2mat(textscan(fid,'%f %f'));
fclose(fid);


% ---------------------------------------------------------------

%Position plot
%Subplot with Earth and Jupiter
%Different timesteps (1day,2mnd)
%1000 year simulations

figure(17)
title('Totaltime = 1000 Year, dT = 1 day');
h1 = plot(JE_Earth_day(:,1),JE_Earth_day(:,2),'red');
hold on
h2 = plot(JE_Jupiter_day(:,1),JE_Jupiter_day(:,2),'blue');
legend([h1 h2],['Earth'],['Jupiter'])
xlabel('AU')
ylabel('AU')

figure(18)
title('Totaltime = 1000 Year, dT = 2 mnd');
h1 = plot(JE_Earth_2mnd(:,1),JE_Earth_2mnd(:,2),'red');
hold on
h2 = plot(JE_Jupiter_2mnd(:,1),JE_Jupiter_2mnd(:,2),'blue');
legend([h1 h2],['Earth'],['Jupiter'])
xlabel('AU')
ylabel('AU')

% ------------------- Conserved values -----------------------------

%Total Energy 1day
figure(19)
title('Total Energy, Totaltime = 1000 year, dT = 1day');
h1 = plot(JE_Cons_1day(:,2)+JE_Cons_1day(:,1),'red');
legend([h1],['Tot. Energy, dt = 1day'])
xlabel('# timestep')

%Total Energy 2mnd
figure(20)
title('Total Energy, Totaltime = 1000 year, dT = 2mnd');
h2 = plot(JE_Cons_2mnd(:,2)+JE_Cons_2mnd(:,2),'blue');
legend([h2],['Tot. Energy. dt = 2mnd'])
xlabel('# timestep')

%------------------------------------------------------------------------

%Position plot
%Subplot of Earth with changed Jupiter mass(10,1000).
%timestep 1day
%1000 year simulations

figure(21)
title('Totaltime = 1000 Year, dT = 1 day, Jupiter mass = 10x');
h1 = plot(JE_Earth_J10(:,1),JE_Earth_J10(:,2),'red');
hold on
h2 = plot(JE_Jupiter_J10(:,1),JE_Jupiter_J10(:,2),'blue');
legend([h1 h2],['Earth'],['Jupiter'])
xlabel('AU')
ylabel('AU')

figure(22)
title('Totaltime = 1000 Year, dT = 1 day, Jupiter mass = 1000x');
h1 = plot(JE_Earth_J1000(:,1),JE_Earth_J1000(:,2),'red');
hold on
h2 = plot(JE_Jupiter_J1000(:,1),JE_Jupiter_J1000(:,2),'blue');
legend([h1 h2],['Earth'],['Jupiter'])
xlim([-10,10])
ylim([-10,10])
xlabel('AU')
ylabel('AU')

%% Oppgave 3f) Full solar system

%1000years
%dt 1day

%Read in correct files
%Earth position dt = 1day.
fid = fopen('Full_VerletValuesEarth.txt');
Full_Earth = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Mars position dt = 1day.
fid = fopen('Full_VerletValuesMars.txt');
Full_Mars = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Merkur position dt = 1day.
fid = fopen('Full_VerletValuesMercury.txt');
Full_Mercur = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Venus position dt = 1day.
fid = fopen('Full_VerletValuesVenus.txt');
Full_Venus = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Jupiter position dt = 1day.
fid = fopen('Full_VerletValuesJupiter.txt');
Full_Jupiter = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Saturn position dt = 1day.
fid = fopen('Full_VerletValuesSaturn.txt');
Full_Saturn = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Ur Anus position dt = 1day.
fid = fopen('Full_VerletValuesUranus.txt');
Full_Uranus = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

%Neptun position dt = 1day.
fid = fopen('Full_VerletValuesNeptune.txt');
Full_Neptun = cell2mat(textscan(fid,'%f %f'));
fclose(fid);

figure(23)
set(gca,'Color','k')
title('Totaltime = 1000 Year, dT = 1 day');
h1 = plot(Full_Mercur(:,1),Full_Mercur(:,2));
hold on
h2 = plot(Full_Venus(:,1),Full_Venus(:,2));
hold on
h3 = plot(Full_Earth(:,1),Full_Earth(:,2));
hold on
h4 = plot(Full_Mars(:,1),Full_Mars(:,2));
hold on
h5 = plot(Full_Jupiter(:,1), Full_Jupiter(:,2));
hold on
h6 = plot(Full_Saturn(:,1), Full_Saturn(:,2));
hold on
h8 = plot(Full_Neptun(:,1), Full_Neptun(:,2));
hold on
h7 = plot(Full_Uranus(:,1), Full_Uranus(:,2));
legend([h1 h2 h3 h4],['Mercur'],['Venus'], ['Earth'],['Mars']);
xlim([-2,2])
ylim([-2,2])
xlabel('AU')
ylabel('AU')

%% Mercur periphelon

%Venus position dt = 1day.
fid = fopen('Rel_PeriphelonMercury.txt');
Periphelon_theta_rel = cell2mat(textscan(fid,'%f'));
fclose(fid);

fid = fopen('Newt_PeriphelonMercury.txt');
Periphelon_theta_newt = cell2mat(textscan(fid,'%f'));
fclose(fid);

figure(24)
h1 = plot(Periphelon_theta_rel);
hold on
ylabel('radians')
legend([h1], ['With relative correction'])
xlabel('Periphelon number')


figure(25)
h2 = plot(Periphelon_theta_newt);
ylabel('radians')
legend([h1], ['Without relative correction'])
xlabel('Periphelon number')






